In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/raw/master_parking_dataset (1).csv")

In [3]:
print("Dataset shape:", df.shape)

Dataset shape: (31025, 13)

In [4]:
df.head()

,date,time,day_of_week,day_of_week_num,is_weekend,parking_area_id,total_slots,occupied_slots,available,occupancy,distance,price,user_selected
0,2025-01-01,06:00,Wednesday,2,0,A01,100,10,90,10.0,0.79,30,1
1,2025-01-01,07:00,Wednesday,2,0,A01,100,18,82,18.0,0.73,30,1
2,2025-01-01,08:00,Wednesday,2,0,A01,100,19,81,19.0,0.88,30,1
3,2025-01-01,09:00,Wednesday,2,0,A01,100,24,76,24.0,0.76,30,1
4,2025-01-01,10:00,Wednesday,2,0,A01,100,22,78,22.0,0.77,30,1

In [5]:
print("Dataset shape:", df.shape)

Dataset shape: (31025, 13)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31025 entries, 0 to 31024
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             31025 non-null  str
 1   time             31025 non-null  str
 2   day_of_week      31025 non-null  str
 3   day_of_week_num  31025 non-null  int64
 4   is_weekend       31025 non-null  int64
 5   parking_area_id  31025 non-null  str
 6   total_slots      31025 non-null  int64
 7   occupied_slots   31025 non-null  int64
 8   available        31025 non-null  int64
 9   occupancy        31025 non-null  float64
 10  distance         31025 non-null  float64
 11  price            31025 non-null  int64
 12  user_selected    31025 non-null  int64
dtypes: float64(2), int64(7), str(4)
memory usage: 3.8 MB

In [7]:
df.describe()

,day_of_week_num,is_weekend,total_slots,occupied_slots,available,occupancy,distance,price,user_selected
count,31025.000000,31025.000000,31025.00000,31025.000000,31025.000000,31025.000000,31025.000000,31025.000000,31025.000000
mean,2.997260,0.284932,130.00000,37.035778,92.964222,26.889686,1.799847,27.609508,0.717937
std,1.997974,0.451389,41.95303,26.773784,30.417969,13.905598,0.822248,5.919849,0.450011
min,0.000000,0.000000,80.00000,2.000000,41.000000,1.670000,0.510000,15.000000,0.000000
25%,1.000000,0.000000,100.00000,18.000000,70.000000,16.250000,1.150000,25.000000,0.000000
50%,3.000000,0.000000,120.00000,30.000000,86.000000,25.000000,1.600000,28.000000,1.000000
75%,5.000000,1.000000,150.00000,49.000000,110.000000,35.830000,2.350000,30.000000,1.000000
max,6.000000,1.000000,200.00000,157.000000,196.000000,78.500000,3.370000,40.000000,1.000000

In [8]:
df.isnull().sum()

date               0
time               0
day_of_week        0
day_of_week_num    0
is_weekend         0
parking_area_id    0
total_slots        0
occupied_slots     0
available          0
occupancy          0
distance           0
price              0
user_selected      0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
invalid_slots = df[
    df["occupied_slots"] + df["available"] != df["total_slots"]
]

print("Invalid slot records:", len(invalid_slots))

Invalid slot records: 0

In [11]:
calculated_occupancy = (
    df["occupied_slots"] / df["total_slots"]
) * 100

difference = (
    calculated_occupancy - df["occupancy"]
).abs()

print("Maximum difference:", difference.max())

Maximum difference: 0.0033333333333445125

In [12]:
print(df[["occupied_slots", "total_slots", "occupancy"]].head(10))

   occupied_slots  total_slots  occupancy
0              10          100       10.0
1              18          100       18.0
2              19          100       19.0
3              24          100       24.0
4              22          100       22.0
5              22          100       22.0
6              22          100       22.0
7              34          100       34.0
8              30          100       30.0
9              28          100       28.0

In [13]:
invalid_occupancy = df[
    (df["occupancy"] < 0) |
    (df["occupancy"] > 100)
]

print("Invalid occupancy records:", len(invalid_occupancy))

Invalid occupancy records: 0

In [14]:
invalid_slots = df[
    df["occupied_slots"] + df["available"] != df["total_slots"]
]

print("Invalid slot records:", len(invalid_slots))

Invalid slot records: 0

In [15]:
calculated_occupancy = (
    df["occupied_slots"] / df["total_slots"]
) * 100

difference = (
    calculated_occupancy - df["occupancy"]
).abs()

print("Maximum difference:", difference.max())

Maximum difference: 0.0033333333333445125

In [16]:
print(df[["occupied_slots", "total_slots", "occupancy"]].head(10))

   occupied_slots  total_slots  occupancy
0              10          100       10.0
1              18          100       18.0
2              19          100       19.0
3              24          100       24.0
4              22          100       22.0
5              22          100       22.0
6              22          100       22.0
7              34          100       34.0
8              30          100       30.0
9              28          100       28.0

In [17]:
invalid_occupancy = df[
    (df["occupancy"] < 0) |
    (df["occupancy"] > 100)
]

print("Invalid occupancy records:", len(invalid_occupancy))

Invalid occupancy records: 0

In [18]:
df["date"] = pd.to_datetime(df["date"])

In [19]:
df["date"].dtype

dtype('<M8[us]')

In [20]:
df["hour"] = pd.to_datetime(df["time"]).dt.hour

C:\Users\VAMSI KRISHNA JAMI\AppData\Local\Temp\ipykernel_6428\1705072889.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["hour"] = pd.to_datetime(df["time"]).dt.hour

In [21]:
df[["time", "hour"]].head(10)

    time  hour
0  06:00     6
1  07:00     7
2  08:00     8
3  09:00     9
4  10:00    10
5  11:00    11
6  12:00    12
7  13:00    13
8  14:00    14
9  15:00    15

In [22]:
df["day"] = df["date"].dt.day

In [23]:
df[["date", "day"]].head()

        date  day
0 2025-01-01    1
1 2025-01-01    1
2 2025-01-01    1
3 2025-01-01    1
4 2025-01-01    1

In [24]:
df["month"] = df["date"].dt.month

In [25]:
df[["date", "month"]].head()

        date  month
0 2025-01-01      1
1 2025-01-01      1
2 2025-01-01      1
3 2025-01-01      1
4 2025-01-01      1

In [26]:
df[
    [
        "date",
        "time",
        "hour",
        "day",
        "month",
        "day_of_week",
        "day_of_week_num",
        "is_weekend"
    ]
].head(10)

        date   time  hour  day  month day_of_week  day_of_week_num  is_weekend
0 2025-01-01  06:00     6    1      1   Wednesday                2           0
1 2025-01-01  07:00     7    1      1   Wednesday                2           0
2 2025-01-01  08:00     8    1      1   Wednesday                2           0
3 2025-01-01  09:00     9    1      1   Wednesday                2           0
4 2025-01-01  10:00    10    1      1   Wednesday                2           0
5 2025-01-01  11:00    11    1      1   Wednesday                2           0
6 2025-01-01  12:00    12    1      1   Wednesday                2           0
7 2025-01-01  13:00    13    1      1   Wednesday                2           0
8 2025-01-01  14:00    14    1      1   Wednesday                2           0
9 2025-01-01  15:00    15    1      1   Wednesday                2           0

In [27]:
df = df.sort_values(
    ["parking_area_id", "date", "time"]
).reset_index(drop=True)

In [28]:
df["previous_occupancy"] = (
    df.groupby("parking_area_id")["occupancy"].shift(1)
)

In [29]:
df[
    [
        "parking_area_id",
        "date",
        "time",
        "occupancy",
        "previous_occupancy"
    ]
].head(15)

   parking_area_id       date   time  occupancy  previous_occupancy
0              A01 2025-01-01  06:00       10.0                 NaN
1              A01 2025-01-01  07:00       18.0                10.0
2              A01 2025-01-01  08:00       19.0                18.0
3              A01 2025-01-01  09:00       24.0                19.0
4              A01 2025-01-01  10:00       22.0                24.0
5              A01 2025-01-01  11:00       22.0                22.0
6              A01 2025-01-01  12:00       22.0                22.0
7              A01 2025-01-01  13:00       34.0                22.0
8              A01 2025-01-01  14:00       30.0                34.0
9              A01 2025-01-01  15:00       28.0                30.0
10             A01 2025-01-01  16:00       34.0                28.0
11             A01 2025-01-01  17:00       48.0                34.0
12             A01 2025-01-01  18:00       52.0                48.0
13             A01 2025-01-01  19:00       29.0                52.0
14             A01 2025-01-01  20:00       23.0                29.0

In [30]:
df["target_occupancy"] = (
    df.groupby("parking_area_id")["occupancy"].shift(-1)
)

In [31]:
df = df.dropna(
    subset=["previous_occupancy", "target_occupancy"]
).reset_index(drop=True)

In [32]:
print("Rows after removing NaN:", len(df))
print(
    df[
        ["previous_occupancy", "target_occupancy"]
    ].isnull().sum()
)

Rows after removing NaN: 31015
previous_occupancy    0
target_occupancy      0
dtype: int64

In [33]:
features = [
    "hour",
    "day_of_week_num",
    "is_weekend",
    "month",
    "previous_occupancy",
    "total_slots",
    "parking_area_id"
]

target = "target_occupancy"

In [34]:
model_df = df[features + [target]].copy()

In [35]:
print("Model dataset shape:", model_df.shape)
model_df.head()

Model dataset shape: (31015, 8)

,hour,day_of_week_num,is_weekend,month,previous_occupancy,total_slots,parking_area_id,target_occupancy
0,7,2,0,1,10.0,100,A01,19.0
1,8,2,0,1,18.0,100,A01,24.0
2,9,2,0,1,19.0,100,A01,22.0
3,10,2,0,1,24.0,100,A01,22.0
4,11,2,0,1,22.0,100,A01,22.0

In [36]:
model_df = pd.get_dummies(
    model_df,
    columns=["parking_area_id"],
    drop_first=True,
    dtype=int
)

In [37]:
print("Model dataset shape:", model_df.shape)
model_df.head()

Model dataset shape: (31015, 11)

,hour,day_of_week_num,is_weekend,month,previous_occupancy,total_slots,target_occupancy,parking_area_id_A02,parking_area_id_A03,parking_area_id_A04,parking_area_id_A05
0,7,2,0,1,10.0,100,19.0,0,0,0,0
1,8,2,0,1,18.0,100,24.0,0,0,0,0
2,9,2,0,1,19.0,100,22.0,0,0,0,0
3,10,2,0,1,24.0,100,22.0,0,0,0,0
4,11,2,0,1,22.0,100,22.0,0,0,0,0

In [38]:
X = model_df.drop(columns=["target_occupancy"])
y = model_df["target_occupancy"]

In [39]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (31015, 10)
y shape: (31015,)

In [40]:
df = df.sort_values(
    ["date", "time", "parking_area_id"]
).reset_index(drop=True)

In [41]:
model_df = df[features + [target]].copy()

model_df = pd.get_dummies(
    model_df,
    columns=["parking_area_id"],
    drop_first=True,
    dtype=int
)

In [42]:
X = model_df.drop(columns=["target_occupancy"])
y = model_df["target_occupancy"]

In [43]:
split_index = int(len(X) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

In [44]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (24812, 10)
X_test : (6203, 10)
y_train: (24812,)
y_test : (6203,)

In [45]:
print("Training period:")
print(df.iloc[:split_index][["date", "time"]].head(1))
print(df.iloc[:split_index][["date", "time"]].tail(1))

print("\nTesting period:")
print(df.iloc[split_index:][["date", "time"]].head(1))
print(df.iloc[split_index:][["date", "time"]].tail(1))

Training period:
        date   time
0 2025-01-01  07:00
            date   time
24811 2025-10-19  22:00

Testing period:
            date   time
24812 2025-10-19  22:00
            date   time
31014 2025-12-31  21:00

In [46]:
from sklearn.linear_model import LinearRegression

In [47]:
linear_model = LinearRegression()

In [48]:
linear_model.fit(X_train, y_train)

LinearRegression()

In [49]:
y_pred_linear = linear_model.predict(X_test)

In [50]:
comparison = pd.DataFrame({
    "Actual": y_test.values[:10],
    "Predicted": y_pred_linear[:10]
})

comparison

   Actual  Predicted
0    2.50   1.042913
1    9.50   6.563532
2    1.67   2.441001
3    5.00  14.736004
4   12.00  25.881074
5    5.00  16.996063
6   11.50  25.216939
7   10.83  15.184706
8   15.00  16.766701
9   18.00  15.050840

In [51]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [52]:
mae_linear = mean_absolute_error(y_test, y_pred_linear)

rmse_linear = np.sqrt(
    mean_squared_error(y_test, y_pred_linear)
)

r2_linear = r2_score(y_test, y_pred_linear)

In [53]:
print("Linear Regression")
print("------------------")
print("MAE :", mae_linear)
print("RMSE:", rmse_linear)
print("R²  :", r2_linear)

Linear Regression
------------------
MAE : 7.488596230757467
RMSE: 9.552397319604962
R²  : 0.5007358099106001

In [54]:
from sklearn.ensemble import RandomForestRegressor

In [55]:
rf_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

In [56]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [57]:
y_pred_rf = rf_model.predict(X_test)

In [58]:
mae_rf = mean_absolute_error(y_test, y_pred_rf)

rmse_rf = np.sqrt(
    mean_squared_error(y_test, y_pred_rf)
)

r2_rf = r2_score(y_test, y_pred_rf)

In [60]:
print("Random Forest")

print("MAE :", mae_rf)
print("RMSE:", rmse_rf)
print("R²  :", r2_rf)

Random Forest
MAE : 3.6108182270326536
RMSE: 4.53978710102721
R²  : 0.8872344002184895

In [61]:
from sklearn.ensemble import GradientBoostingRegressor

In [62]:
gb_model = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

In [63]:
gb_model.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, n_estimators=200, random_state=42)

In [64]:
y_pred_gb = gb_model.predict(X_test)

In [65]:
mae_gb = mean_absolute_error(y_test, y_pred_gb)

rmse_gb = np.sqrt(
    mean_squared_error(y_test, y_pred_gb)
)

r2_gb = r2_score(y_test, y_pred_gb)

In [66]:
print("Gradient Boosting")

print("MAE :", mae_gb)
print("RMSE:", rmse_gb)
print("R²  :", r2_gb)

Gradient Boosting
MAE : 3.433709972396766
RMSE: 4.3221080474561555
R²  : 0.8977891734970714

In [67]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "Gradient Boosting"
    ],
    "MAE": [
        mae_linear,
        mae_rf,
        mae_gb
    ],
    "RMSE": [
        rmse_linear,
        rmse_rf,
        rmse_gb
    ],
    "R2": [
        r2_linear,
        r2_rf,
        r2_gb
    ]
})

results

               Model       MAE      RMSE        R2
0  Linear Regression  7.488596  9.552397  0.500736
1      Random Forest  3.610818  4.539787  0.887234
2  Gradient Boosting  3.433710  4.322108  0.897789

In [68]:
results.sort_values("MAE")

               Model       MAE      RMSE        R2
2  Gradient Boosting  3.433710  4.322108  0.897789
1      Random Forest  3.610818  4.539787  0.887234
0  Linear Regression  7.488596  9.552397  0.500736

In [69]:
best_model_name = results.loc[
    results["RMSE"].idxmin(),
    "Model"
]

print("Best model:", best_model_name)

Best model: Gradient Boosting

In [70]:
model_map = {
    "Linear Regression": linear_model,
    "Random Forest": rf_model,
    "Gradient Boosting": gb_model
}

best_model = model_map[best_model_name]

print(type(best_model))

<class 'sklearn.ensemble._gb.GradientBoostingRegressor'>

In [71]:
best_predictions = best_model.predict(X_test)

comparison = pd.DataFrame({
    "Actual": y_test.values[:20],
    "Predicted": best_predictions[:20]
})

comparison

    Actual  Predicted
0     2.50   5.133667
1     9.50   8.633183
2     1.67   6.787278
3     5.00   8.224987
4    12.00  13.838932
5     5.00   6.610485
6    11.50  15.719408
7    10.83  10.048441
8    15.00  12.430838
9    18.00  17.923403
10    8.75  10.230347
11   24.00  21.060280
12   14.17  15.585422
13   18.00  14.938639
14   25.33  21.455863
15   16.25  12.582581
16   22.00  23.818693
17   23.33  18.354849
18   10.00  17.738718
19   20.00  22.941214

In [72]:
best_mae = mean_absolute_error(
    y_test,
    best_predictions
)

best_rmse = np.sqrt(
    mean_squared_error(y_test, best_predictions)
)

best_r2 = r2_score(
    y_test,
    best_predictions
)

print("FINAL MODEL")
print("-----------")
print("Model:", best_model_name)
print("MAE :", best_mae)
print("RMSE:", best_rmse)
print("R²  :", best_r2)

FINAL MODEL
-----------
Model: Gradient Boosting
MAE : 3.433709972396766
RMSE: 4.3221080474561555
R²  : 0.8977891734970714

In [73]:
import joblib

In [74]:
joblib.dump(
    best_model,
    "../models/occupancy_model.pkl"
)

['../models/occupancy_model.pkl']

In [75]:
print("Model:", best_model_name)
print("MAE:", best_mae)
print("RMSE:", best_rmse)
print("R²:", best_r2)

Model: Gradient Boosting
MAE: 3.433709972396766
RMSE: 4.3221080474561555
R²: 0.8977891734970714